#include <lua/lua.h>
#include <lua/luaconf.h>
#include "limits.h"
#include "lobject.h"
#include "lzio.h"
#include "lstate.h"
#include "lfunc.h"
#include "ldo.h"
#include "llex.h"
#include "lparser.h"
#include "lcode.h"
#include "ldebug.h"