name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  linux-build:
    name: "linux build"
    runs-on: "ubuntu-20.04"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: "Build & test"
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
          cd ${{github.workspace}}/build && cpack -G DEB
          cd ${{github.workspace}}/build && cpack -G ZIP

  windows-build:
    name: "windows build"
    runs-on: "windows-2022"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: "Build & test"
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

  darwin-build:
    name: "darwin build"
    runs-on: "macos-latest"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: "Build & test"
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

