---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  linux-build:
    name: "linux build"
    runs-on: "ubuntu-20.04"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: "Build & test"
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
          cd ${{github.workspace}}/build && cpack -G ZIP

      - uses: actions/upload-artifact@master
        with:
          name: linux-artifact
          path: ${{github.workspace}}/build/packages/

      
  windows-build:
    name: "windows build"
    runs-on: "windows-2002"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: "Build & test"
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
          cd ${{github.workspace}}/build && cpack -G ZIP

      - uses: actions/upload-artifact@master
        with:
          name: windows-artifact
          path: ${{github.workspace}}/build/packages/

  release:
    name: "release"
    runs-on: "ubuntu-20.04"
    needs:
      - linux-build
      - windows-build
    steps:
      - uses: actions/download-artifact@master
        with:
          name: linux-artifact
          path: linux/

      - uses: actions/download-artifact@master
        with:
          name: windows-artifact
          path: windows/

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            windows
            linux
