---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  linux-build:
    name: "linux build"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3

      - name: "Build & test"
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - uses: actions/upload-artifact@master
        with:
          name: linux-artifact
          path: ${{github.workspace}}/build/bin/

      
  windows-build:
    name: "windows build"
    runs-on: "windows-latest"

    steps:
      - uses: actions/checkout@v3

      - name: "Build & test"
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - uses: actions/upload-artifact@master
        with:
          name: windows-artifact
          path: ${{github.workspace}}/build/bin/

  release:
    name: "release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/download-artifact@master
        with:
          name: linux-artifact
          path: linux/

      - uses: actions/download-artifact@master
        with:
          name: window-artifact
          path: window/

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            window
            linux